Import('env')

localenv = env.Clone()

libmdct = localenv.Library('mdct', ['mdct_fft.c'])
Export('libmdct')

localenv.Install('#/include', 'mdct.h')
localenv.Install('#/build', 'mdct_fft.cl')
localenv.Install('#/exec', 'mdct_fft.cl')
