Import('env')

localenv = env.Clone()

env.ParseConfig('pkg-config --cflags --libs fftw3')

env.Program( target='fft', source=["main.cpp"] )
env.Program( target='fft_fftw', source=["fft_test_fftw.c"] )
